accounts/urls.py
from django.urls import path
from .views import SignUpView

urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
]

pages/urls.py
from django.urls import path

from .views import HomePageView

urlpatterns = [
    path("", HomePageView.as_view(), name="home")
]

projects/urls.py
from django.urls import path

from .views import (
    ProjectListView,
    ProjectDetailView,
    ProjectUpdateView,
    ProjectDeleteView,
    ProjectCreateView,

)

urlpatterns = [
    path("<int:pk>/", ProjectDetailView.as_view(),
        name="project_detail"),
    path("<int:pk>/edit/", ProjectUpdateView.as_view(),
        name="project_edit"),
    path("<int:pk>/delete/", ProjectDeleteView.as_view(),
        name="project_delete"),
    path("new/", ProjectCreateView.as_view(), name="project_new"),
    path("", ProjectListView.as_view(), name="project_list"),
]

settings/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path("__reload__", include("django_browser_reload.urls")),
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("projects/", include("projects.urls")),
    path("", include("pages.urls")),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


# Create your models here.

class CustomUser(AbstractUser):
    age = models.PositiveIntegerField(null=True, blank=True)

pages/models.py
from django.db import models

# Create your models here.

projects/models.py
from pyexpat import model
from django.conf import settings
from django.db import models
from django.urls import reverse

class Project(models.Model):
    title = models.CharField(max_length=255)
    overview = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("project_detail", kwargs={"pk": self.pk})

class ProjectUpdate(models.Model):
    title = models.CharField(max_length=255)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    udpate = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("project_list")

class ProjectComment(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    comment = models.CharField(max_length=140)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.comment
    
    def get_absolute_url(self):
        return reverse("project_list")
    

accounts/forms.py
from dataclasses import field
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = CustomUser
        fields = {
            "username",
            "email",
        }

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = (
            "username",
            "email",
            "age",
        )

projects/forms.py
from django import forms

from .models import ProjectComment

class ProjectCommentForm(forms.ModelForm):
    class Meta:
        model = ProjectComment
        fields = ("comment", "author")

accounts/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import CustomUserCreationForm

class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name: str = "registration/signup.html"

# Create your views here.

pages/views.py
from django.views.generic import TemplateView

class HomePageView(TemplateView):
    template_name = "home.html"

# Create your views here.

projects/views.py
from pickle import FALSE
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    UserPassesTestMixin
)
from django.views.generic import ListView, DetailView, FormView
from django.views.generic.detail import SingleObjectMixin
from django.views.generic.edit import (
    UpdateView, DeleteView, CreateView
)
from django.views import View
from django.urls import reverse_lazy, reverse

from .forms import ProjectCommentForm

from .models import Project

class CommentGet(DetailView):
    model = Project
    template_name: str = "project/project_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = ProjectCommentForm()
        return context


class CommentPost(SingleObjectMixin, FormView):
    model = Project
    form_class = ProjectCommentForm
    template_name: str = "project/project_detail.html"

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.project = self.object
        comment.save()
        return super().form_valid(form)
    
    def get_success_url(self):
        project = self.get_object()
        return reverse("project_detail", kwargs={"pk": project.pkcv})



class ProjectListView(LoginRequiredMixin, ListView):
    model = Project
    template_name: str = "project/project_list.html"


class ProjectDetailView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        view = CommentGet.as_view()
        return view(request, *args, **kwargs)
    
    def post(self, request, *args, **kwargs):
        view = CommentPost.as_view()
        return view(request, *args, **kwargs)


class ProjectUpdateView(
    LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Project
    fields = (
        "title",
        "overview",
    )
    template_name: str = "project/project_edit.html"

    def test_func(self):
        obj = self.get_object()
        return obj.author == self.request.user


class ProjectDeleteView(
    LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Project
    template_name: str = "project/project_delete.html"
    success_url = reverse_lazy("project_list")

    def test_func(self):
        obj = self.object()
        return obj.author == self.request.user

class ProjectCreateView(LoginRequiredMixin, CreateView):
    model = Project
    template_name: str = "project/project_new.html"
    fields = ("title", "overview")

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

templates/base.html
{% load tailwind_tags %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{% block title %}Disrat Studios{% endblock title %}</title>
    <meta name="viewport" content="width=device-width,
    initial-scale=1, shrink-to-fit=no">

    <!-- Tailwind -->
    {% tailwind_css %}

</head>

<body class="bg-black-50 font-serif leading-normal tracking-normal">
    <div class="container mx-auto">
        <section class="flex items-center justify-center h-screen">
            <h1 class="text-5xl">Django + Tailwind = ❤️</h1>
        </section>
    </div>
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock title %}

{% block content %}
{% if user.is_authenticated %}
    Hi {{ user.username }}!
    <p><a href="{% url 'logout' %}">Log out</a></p>
{% else %}
    <p>You are not logged in</p>
    <a href="{% url 'login' %}">Log in</a> |
    <a href="{% url 'signup' %}">Sign Up</a>
{% endif %}
{% endblock content %}

templates/project/project_delete.html
{% extends 'base.html' %}

{% block content %}
<h1>Delete</h1>
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ project.title }}"></p>
    <button class="btn btn-danger ml-2" type="submit">Confirm</button>
</form>
{% endblock content %}

templates/project/project_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="article-entry">
    <h2>{{ object.title }}</h2>
    <p>by {{ object.author }} | {{ object.date }}</p>
    <p>{{ object.overview }}</p>
</div>

<hr>
<h4>Comments</h4>
{% for projectcomment in project.projectcomment_set.all %}
    <p>{{ projectcomment.author }} &middot; {{ projectcomment }}</p>
{% endfor %}
<hr>

<h4>Add a comment</h4>
    <form action="" method="post">{% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-success ml-2" type="submit">Save</button>
    </form>


<p><a href="{% url 'project_edit' project.pk %}">Edit</a> |
    <a href="{% url 'project_delete' project.pk %}">Delete</a></p>
<p>Back to <a href="{% url 'project_list' %}">All Projects</a>.</p>
{% endblock content %}

templates/project/project_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<h1>Edit</h1>
<form action="" method="post">{% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-info ml-2" type="submit">Update</button>
</form>
{% endblock content %}

templates/project/project_list.html
{% extends 'base.html' %}

{% block title %}Projects{% endblock title %}

{% block content %}
{% for project in project_list %}
    <div class="card">
        <div class="card-header">
            <span class="font-weight-bold"><a href="{% url 'project_detail' project.pk %}">{{ project.title }}</a></span> &middot;
            <span class="text-muted">by {{ project.author }} |
            {{ project.date }}</span>
        </div>
        <div class="card-body">
            <p>{{ project.overview }}</p>
            <a href="{% url 'project_edit' project.pk %}">Edit</a> |
            <a href="{% url 'project_delete' project.pk %}">Delete</a>
        </div>
        <div class="card-footer">
            {% for projectcomment in project.projectcomment_set.all %}
            <p>
                <span class="font-weight-bold">
                    {{ projectcomment.author }} &middot;
                </span>
                {{ projectcomment }}
            </p>
            {% endfor %}
        </div>
    </div>
    <br />
{% endfor %}
{% endblock content %}

templates/project/project_new.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<h1>New Project</h1>
<form action="" method="post">{% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-success ml-2" type="submit">Save</button>
</form>
{% endblock content %}

templates/project_list.html
{% extends 'base.html' %}

{% block title %}Projects{% endblock title %}

{% block content %}
{% for project in project_list %}
    <div class="card">
        <div class="card-header">
            <span class="font-weight-bold">{{ project.title }}</span> &middot;
            <span class="text-muted">by {{ project.author }} |
            {{ project.date }}</span>
        </div>
        <div class="card-body">
            {{ project.overview }}
        </div>
        <div class="card-footer text-center text-muted">
            <a href="#">Edit</a> | <a href="#">Delete</a>
        </div>
    </div>
    <br />
{% endfor %}
{% endblock content %}